services:
  - type: web
    plan: free
    name: second-test
    region: ohio
    env: node
    buildCommand: "npm ci && npm run build"
    startCommand: "npm start"
    envVars:
      - key: TEST_ENV
        sync: false
      - fromGroup: staging