services:
  - type: web
    plan: free
    name: second-test
    region: ohio
    env: node
    buildCommand: "npm ci && npm run build"
    startCommand: "npm start"
    envVars:
      - key: ANOTHER_ENV_VAR
        value: "other"
      - key: SHOULD_COPY
        value: "prod"
        previewValue: "preview"
      - key: DONT_COPY
        sync: false
      - fromGroup: shared